# Generated by Django 4.2.13 on 2026-05-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Export'), ('utility', 'Utility Portal'), ('travel', 'Corporate Travel')], max_length=20)),
                ('source_row_index', models.IntegerField(blank=True, null=True)),
                ('source_row_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 – Direct'), ('2', 'Scope 2 – Electricity'), ('3', 'Scope 3 – Value chain')], max_length=1)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('procurement', 'Procurement'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel Stay'), ('ground_transport', 'Ground Transport')], max_length=30)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=50)),
                ('raw_description', models.TextField(blank=True)),
                ('normalised_quantity', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('normalised_unit', models.CharField(blank=True, max_length=20)),
                ('emission_factor_key', models.CharField(blank=True, max_length=100)),
                ('emission_factor_value', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('kg_co2e', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_period_start', models.DateField(blank=True, null=True)),
                ('activity_period_end', models.DateField(blank=True, null=True)),
                ('reporting_year', models.IntegerField()),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked for Audit')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manually_edited', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.ingestionbatch')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='accounts.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emission_records',
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['organisation', 'reporting_year', 'status'], name='emission_re_organis_52c80b_idx'), models.Index(fields=['organisation', 'scope', 'reporting_year'], name='emission_re_organis_c472e4_idx'), models.Index(fields=['source_type', 'ingestion_batch'], name='emission_re_source__cda8e1_idx')],
            },
        ),
    ]
