# Generated by Django 4.2.13 on 2026-05-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Export'), ('utility', 'Utility Portal CSV'), ('travel', 'Corporate Travel')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='ingestion/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_success', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('rows_duplicate', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_batches', to='accounts.organisation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingestion_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.TextField(blank=True)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='ingestion.ingestionbatch')),
            ],
            options={
                'db_table': 'ingestion_errors',
                'ordering': ['row_index'],
            },
        ),
    ]
